# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_body.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(870, 593)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(870, 593))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("\n"
"background-color: rgb(39, 39, 39);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_header.setStyleSheet("QFrame{\n"
"    border-bottom:  2px solid #000;\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.main_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_bar = QtWidgets.QFrame(self.main_header)
        self.title_bar.setStyleSheet("")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menu_logo = QtWidgets.QFrame(self.title_bar)
        self.menu_logo.setEnabled(True)
        self.menu_logo.setMinimumSize(QtCore.QSize(0, 45))
        self.menu_logo.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menu_logo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_logo.setStyleSheet("QFrame{\n"
"    background-color:#000;\n"
"}\n"
"QPushButton {\n"
"    padding: 5px 10px;\n"
"    border: none;\n"
"    border-radius:5px;\n"
"    background-color:#000;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 97, 157);\n"
"}")
        self.menu_logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_logo.setObjectName("menu_logo")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.menu_logo)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_btn = QtWidgets.QPushButton(self.menu_logo)
        self.menu_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.menu_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menu_btn.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 97, 157);\n"
"}")
        self.menu_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon/icons8_menu_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn.setIcon(icon)
        self.menu_btn.setIconSize(QtCore.QSize(32, 32))
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout_4.addWidget(self.menu_btn)
        self.horizontalLayout_5.addWidget(self.menu_logo)
        self.title_bar_add = QtWidgets.QFrame(self.title_bar)
        self.title_bar_add.setFrameShape(QtWidgets.QFrame.Panel)
        self.title_bar_add.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar_add.setObjectName("title_bar_add")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.title_bar_add)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.title_bar_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.horizontalLayout_5.addWidget(self.title_bar_add)
        self.horizontalLayout_2.addWidget(self.title_bar)
        self.window_navigation = QtWidgets.QFrame(self.main_header)
        self.window_navigation.setMaximumSize(QtCore.QSize(100, 16777215))
        self.window_navigation.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 97, 157);\n"
"}")
        self.window_navigation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_navigation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_navigation.setObjectName("window_navigation")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.window_navigation)
        self.horizontalLayout_3.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimum_btn = QtWidgets.QPushButton(self.window_navigation)
        self.minimum_btn.setAutoFillBackground(False)
        self.minimum_btn.setStyleSheet("")
        self.minimum_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icon/icons8_minimize_window_64px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimum_btn.setIcon(icon1)
        self.minimum_btn.setIconSize(QtCore.QSize(24, 24))
        self.minimum_btn.setObjectName("minimum_btn")
        self.horizontalLayout_3.addWidget(self.minimum_btn)
        self.maximum_btn = QtWidgets.QPushButton(self.window_navigation)
        self.maximum_btn.setStyleSheet("")
        self.maximum_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icon/icons8_maximize_window_64px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximum_btn.setIcon(icon2)
        self.maximum_btn.setIconSize(QtCore.QSize(24, 24))
        self.maximum_btn.setObjectName("maximum_btn")
        self.horizontalLayout_3.addWidget(self.maximum_btn)
        self.close_btn = QtWidgets.QPushButton(self.window_navigation)
        self.close_btn.setStyleSheet("")
        self.close_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icon/icons8_macos_close_64px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon3)
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        self.horizontalLayout_2.addWidget(self.window_navigation)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        self.left_side_menu.setEnabled(True)
        self.left_side_menu.setMaximumSize(QtCore.QSize(45, 16777215))
        self.left_side_menu.setStyleSheet("QFrame{\n"
"    background-color:#000;\n"
"}\n"
"QPushButton {\n"
"    padding: 15px 10px;\n"
"    border: none;\n"
"    border-radius:10px;\n"
"    background-color:#000;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 97, 157);\n"
"}")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.Panel)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_2.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_menu_top_buttons = QtWidgets.QFrame(self.left_side_menu)
        self.left_menu_top_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_top_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_top_buttons.setObjectName("left_menu_top_buttons")
        self.formLayout = QtWidgets.QFormLayout(self.left_menu_top_buttons)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.btn_home = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.btn_home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_home.setStyleSheet("background-image: url(:/images/icon/icons8_home_32px.png);\n"
"background-repeat: none;\n"
"padding-left: 40px;\n"
"background-position: center left;")
        self.btn_home.setIconSize(QtCore.QSize(28, 28))
        self.btn_home.setObjectName("btn_home")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btn_home)
        self.btn_setting = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.btn_setting.setStyleSheet("background-image: url(:/images/icon/icons8_settings_32px.png);\n"
"background-repeat: none;\n"
"padding-left: 40px;\n"
"background-position: center left;")
        self.btn_setting.setIconSize(QtCore.QSize(28, 28))
        self.btn_setting.setObjectName("btn_setting")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.btn_setting)
        self.verticalLayout_2.addWidget(self.left_menu_top_buttons)
        self.btn_information = QtWidgets.QPushButton(self.left_side_menu)
        self.btn_information.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_information.setStyleSheet("background-image: url(:/images/icon/icons8_info_32px.png);\n"
"background-repeat: none;\n"
"padding-left: 30px;\n"
"background-position: center left;")
        self.btn_information.setIconSize(QtCore.QSize(28, 28))
        self.btn_information.setAutoExclusive(False)
        self.btn_information.setObjectName("btn_information")
        self.verticalLayout_2.addWidget(self.btn_information)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.center_main = QtWidgets.QFrame(self.main_body)
        self.center_main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.center_main.setStyleSheet("")
        self.center_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_main.setObjectName("center_main")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.center_main)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stackedWidget = QtWidgets.QStackedWidget(self.center_main)
        self.stackedWidget.setObjectName("stackedWidget")
        self.form_rong = QtWidgets.QWidget()
        self.form_rong.setStyleSheet("color: rgb(255, 255, 255);")
        self.form_rong.setObjectName("form_rong")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.form_rong)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_info = QtWidgets.QFrame(self.form_rong)
        self.frame_info.setStyleSheet("")
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_info)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9.addWidget(self.frame_info)
        self.stackedWidget.addWidget(self.form_rong)
        self.form_control = QtWidgets.QWidget()
        self.form_control.setObjectName("form_control")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.form_control)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_setting = QtWidgets.QFrame(self.form_control)
        self.frame_setting.setStyleSheet("color: rgb(255, 255, 255);")
        self.frame_setting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_setting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_setting.setObjectName("frame_setting")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_setting)
        self.gridLayout.setContentsMargins(10, 30, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_expand = QtWidgets.QFrame(self.frame_setting)
        self.frame_expand.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_expand.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_expand.setObjectName("frame_expand")
        self.txt_endcoder_left = QtWidgets.QLineEdit(self.frame_expand)
        self.txt_endcoder_left.setGeometry(QtCore.QRect(30, 120, 90, 30))
        self.txt_endcoder_left.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_endcoder_left.setMaximumSize(QtCore.QSize(90, 60))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.txt_endcoder_left.setFont(font)
        self.txt_endcoder_left.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_endcoder_left.setObjectName("txt_endcoder_left")
        self.txt_encoder_right = QtWidgets.QLineEdit(self.frame_expand)
        self.txt_encoder_right.setGeometry(QtCore.QRect(140, 120, 90, 30))
        self.txt_encoder_right.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_encoder_right.setMaximumSize(QtCore.QSize(90, 60))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.txt_encoder_right.setFont(font)
        self.txt_encoder_right.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_encoder_right.setObjectName("txt_encoder_right")
        self.lb_encoderticks = QtWidgets.QLabel(self.frame_expand)
        self.lb_encoderticks.setGeometry(QtCore.QRect(90, 80, 90, 30))
        self.lb_encoderticks.setMinimumSize(QtCore.QSize(90, 30))
        self.lb_encoderticks.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lb_encoderticks.setFont(font)
        self.lb_encoderticks.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_encoderticks.setObjectName("lb_encoderticks")
        self.btn_getencoder = QtWidgets.QPushButton(self.frame_expand)
        self.btn_getencoder.setGeometry(QtCore.QRect(70, 20, 120, 45))
        self.btn_getencoder.setMinimumSize(QtCore.QSize(120, 45))
        self.btn_getencoder.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_getencoder.setFont(font)
        self.btn_getencoder.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_getencoder.setIconSize(QtCore.QSize(24, 24))
        self.btn_getencoder.setObjectName("btn_getencoder")
        self.gridLayout.addWidget(self.frame_expand, 1, 2, 1, 1)
        self.frame_Camera = QtWidgets.QFrame(self.frame_setting)
        self.frame_Camera.setMinimumSize(QtCore.QSize(100, 200))
        self.frame_Camera.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_Camera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Camera.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_Camera.setObjectName("frame_Camera")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_Camera)
        self.formLayout_2.setContentsMargins(5, -1, -1, -1)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lb_mode = QtWidgets.QLabel(self.frame_Camera)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_mode.setFont(font)
        self.lb_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_mode.setObjectName("lb_mode")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lb_mode)
        self.btn_speedmode = QtWidgets.QPushButton(self.frame_Camera)
        self.btn_speedmode.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_speedmode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_speedmode.setFont(font)
        self.btn_speedmode.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_speedmode.setIconSize(QtCore.QSize(24, 24))
        self.btn_speedmode.setObjectName("btn_speedmode")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.btn_speedmode)
        self.btn_positionmode = QtWidgets.QPushButton(self.frame_Camera)
        self.btn_positionmode.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_positionmode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_positionmode.setFont(font)
        self.btn_positionmode.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_positionmode.setIconSize(QtCore.QSize(24, 24))
        self.btn_positionmode.setObjectName("btn_positionmode")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.btn_positionmode)
        self.lb_idle = QtWidgets.QLabel(self.frame_Camera)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_idle.setFont(font)
        self.lb_idle.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_idle.setObjectName("lb_idle")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_idle)
        self.btn_idle = QtWidgets.QPushButton(self.frame_Camera)
        self.btn_idle.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_idle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_idle.setFont(font)
        self.btn_idle.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_idle.setIconSize(QtCore.QSize(24, 24))
        self.btn_idle.setObjectName("btn_idle")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.btn_idle)
        self.btn_enablemotor = QtWidgets.QPushButton(self.frame_Camera)
        self.btn_enablemotor.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_enablemotor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_enablemotor.setFont(font)
        self.btn_enablemotor.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_enablemotor.setIconSize(QtCore.QSize(24, 24))
        self.btn_enablemotor.setObjectName("btn_enablemotor")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btn_enablemotor)
        self.gridLayout.addWidget(self.frame_Camera, 0, 0, 1, 1)
        self.frame_comport = QtWidgets.QFrame(self.frame_setting)
        self.frame_comport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_comport.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_comport.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_comport.setObjectName("frame_comport")
        self.btn_checkvolt = QtWidgets.QPushButton(self.frame_comport)
        self.btn_checkvolt.setGeometry(QtCore.QRect(20, 69, 120, 45))
        self.btn_checkvolt.setMinimumSize(QtCore.QSize(120, 45))
        self.btn_checkvolt.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_checkvolt.setFont(font)
        self.btn_checkvolt.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_checkvolt.setIconSize(QtCore.QSize(24, 24))
        self.btn_checkvolt.setObjectName("btn_checkvolt")
        self.lb_volt = QtWidgets.QLabel(self.frame_comport)
        self.lb_volt.setGeometry(QtCore.QRect(160, 70, 111, 30))
        self.lb_volt.setMinimumSize(QtCore.QSize(90, 30))
        self.lb_volt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lb_volt.setFont(font)
        self.lb_volt.setObjectName("lb_volt")
        self.lb_expand = QtWidgets.QLabel(self.frame_comport)
        self.lb_expand.setGeometry(QtCore.QRect(20, 20, 70, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_expand.setFont(font)
        self.lb_expand.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_expand.setObjectName("lb_expand")
        self.btn_xoay = QtWidgets.QPushButton(self.frame_comport)
        self.btn_xoay.setGeometry(QtCore.QRect(20, 140, 120, 45))
        self.btn_xoay.setMinimumSize(QtCore.QSize(120, 45))
        self.btn_xoay.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xoay.setFont(font)
        self.btn_xoay.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_xoay.setIconSize(QtCore.QSize(24, 24))
        self.btn_xoay.setObjectName("btn_xoay")
        self.gridLayout.addWidget(self.frame_comport, 1, 1, 1, 1)
        self.frame_testcontrol = QtWidgets.QFrame(self.frame_setting)
        self.frame_testcontrol.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_testcontrol.setMaximumSize(QtCore.QSize(16777215, 800))
        self.frame_testcontrol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_testcontrol.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_testcontrol.setLineWidth(1)
        self.frame_testcontrol.setObjectName("frame_testcontrol")
        self.lb_testcontrol = QtWidgets.QLabel(self.frame_testcontrol)
        self.lb_testcontrol.setGeometry(QtCore.QRect(10, 10, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_testcontrol.setFont(font)
        self.lb_testcontrol.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_testcontrol.setObjectName("lb_testcontrol")
        self.lb_sp = QtWidgets.QLabel(self.frame_testcontrol)
        self.lb_sp.setGeometry(QtCore.QRect(10, 220, 90, 30))
        self.lb_sp.setMinimumSize(QtCore.QSize(90, 30))
        self.lb_sp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lb_sp.setFont(font)
        self.lb_sp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_sp.setObjectName("lb_sp")
        self.txt_speed = QtWidgets.QLineEdit(self.frame_testcontrol)
        self.txt_speed.setGeometry(QtCore.QRect(110, 220, 41, 30))
        self.txt_speed.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_speed.setMaximumSize(QtCore.QSize(90, 60))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.txt_speed.setFont(font)
        self.txt_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_speed.setObjectName("txt_speed")
        self.btn_left = QtWidgets.QPushButton(self.frame_testcontrol)
        self.btn_left.setGeometry(QtCore.QRect(10, 100, 71, 51))
        self.btn_left.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_left.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_left.setFont(font)
        self.btn_left.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_left.setIconSize(QtCore.QSize(24, 24))
        self.btn_left.setObjectName("btn_left")
        self.btn_forward = QtWidgets.QPushButton(self.frame_testcontrol)
        self.btn_forward.setGeometry(QtCore.QRect(90, 40, 81, 51))
        self.btn_forward.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_forward.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_forward.setFont(font)
        self.btn_forward.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_forward.setIconSize(QtCore.QSize(24, 24))
        self.btn_forward.setObjectName("btn_forward")
        self.btn_right = QtWidgets.QPushButton(self.frame_testcontrol)
        self.btn_right.setGeometry(QtCore.QRect(180, 100, 71, 51))
        self.btn_right.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_right.setFont(font)
        self.btn_right.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_right.setIconSize(QtCore.QSize(24, 24))
        self.btn_right.setObjectName("btn_right")
        self.btn_stop = QtWidgets.QPushButton(self.frame_testcontrol)
        self.btn_stop.setGeometry(QtCore.QRect(90, 100, 81, 51))
        self.btn_stop.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_stop.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_stop.setFont(font)
        self.btn_stop.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_stop.setIconSize(QtCore.QSize(24, 24))
        self.btn_stop.setObjectName("btn_stop")
        self.btn_backward = QtWidgets.QPushButton(self.frame_testcontrol)
        self.btn_backward.setGeometry(QtCore.QRect(90, 160, 81, 51))
        self.btn_backward.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_backward.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_backward.setFont(font)
        self.btn_backward.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_backward.setIconSize(QtCore.QSize(24, 24))
        self.btn_backward.setObjectName("btn_backward")
        self.btn_keypad = QtWidgets.QPushButton(self.frame_testcontrol)
        self.btn_keypad.setGeometry(QtCore.QRect(190, 214, 71, 31))
        self.btn_keypad.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_keypad.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_keypad.setFont(font)
        self.btn_keypad.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_keypad.setIconSize(QtCore.QSize(24, 24))
        self.btn_keypad.setObjectName("btn_keypad")
        self.gridLayout.addWidget(self.frame_testcontrol, 0, 1, 1, 1)
        self.frame_modeplus = QtWidgets.QFrame(self.frame_setting)
        self.frame_modeplus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_modeplus.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_modeplus.setObjectName("frame_modeplus")
        self.lb_left = QtWidgets.QLabel(self.frame_modeplus)
        self.lb_left.setGeometry(QtCore.QRect(30, 40, 90, 30))
        self.lb_left.setMinimumSize(QtCore.QSize(90, 30))
        self.lb_left.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lb_left.setFont(font)
        self.lb_left.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_left.setObjectName("lb_left")
        self.lb_right = QtWidgets.QLabel(self.frame_modeplus)
        self.lb_right.setGeometry(QtCore.QRect(140, 40, 90, 30))
        self.lb_right.setMinimumSize(QtCore.QSize(90, 30))
        self.lb_right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lb_right.setFont(font)
        self.lb_right.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_right.setObjectName("lb_right")
        self.txt_left = QtWidgets.QLineEdit(self.frame_modeplus)
        self.txt_left.setGeometry(QtCore.QRect(30, 70, 90, 30))
        self.txt_left.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_left.setMaximumSize(QtCore.QSize(90, 60))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.txt_left.setFont(font)
        self.txt_left.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_left.setObjectName("txt_left")
        self.txt_right = QtWidgets.QLineEdit(self.frame_modeplus)
        self.txt_right.setGeometry(QtCore.QRect(140, 70, 90, 30))
        self.txt_right.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_right.setMaximumSize(QtCore.QSize(90, 60))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.txt_right.setFont(font)
        self.txt_right.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_right.setObjectName("txt_right")
        self.btn_runspeed = QtWidgets.QPushButton(self.frame_modeplus)
        self.btn_runspeed.setGeometry(QtCore.QRect(30, 120, 120, 45))
        self.btn_runspeed.setMinimumSize(QtCore.QSize(120, 45))
        self.btn_runspeed.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_runspeed.setFont(font)
        self.btn_runspeed.setStyleSheet("QPushButton {\n"
"    padding: 8px 6px;\n"
"    border: 1px solid rgb(255, 243, 248);\n"
"    border-radius:8px;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 97, 157);\n"
"}")
        self.btn_runspeed.setIconSize(QtCore.QSize(24, 24))
        self.btn_runspeed.setObjectName("btn_runspeed")
        self.lb_testcontrol_2 = QtWidgets.QLabel(self.frame_modeplus)
        self.lb_testcontrol_2.setGeometry(QtCore.QRect(30, 10, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_testcontrol_2.setFont(font)
        self.lb_testcontrol_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_testcontrol_2.setObjectName("lb_testcontrol_2")
        self.gridLayout.addWidget(self.frame_modeplus, 0, 2, 1, 1)
        self.frame_comport_2 = QtWidgets.QFrame(self.frame_setting)
        self.frame_comport_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_comport_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_comport_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_comport_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_comport_2.setObjectName("frame_comport_2")
        self.formLayout_6 = QtWidgets.QFormLayout(self.frame_comport_2)
        self.formLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_6.setHorizontalSpacing(6)
        self.formLayout_6.setVerticalSpacing(12)
        self.formLayout_6.setObjectName("formLayout_6")
        self.lb_portInfo = QtWidgets.QLabel(self.frame_comport_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_portInfo.setFont(font)
        self.lb_portInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_portInfo.setObjectName("lb_portInfo")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_portInfo)
        self.lb_nameport = QtWidgets.QLabel(self.frame_comport_2)
        self.lb_nameport.setMinimumSize(QtCore.QSize(90, 30))
        self.lb_nameport.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lb_nameport.setFont(font)
        self.lb_nameport.setObjectName("lb_nameport")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_nameport)
        self.cbb_nameport = QtWidgets.QComboBox(self.frame_comport_2)
        self.cbb_nameport.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbb_nameport.setStyleSheet("color: rgb(255, 255, 255);")
        self.cbb_nameport.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cbb_nameport.setDuplicatesEnabled(False)
        self.cbb_nameport.setObjectName("cbb_nameport")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbb_nameport)
        self.lb_baudrate = QtWidgets.QLabel(self.frame_comport_2)
        self.lb_baudrate.setMinimumSize(QtCore.QSize(90, 30))
        self.lb_baudrate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lb_baudrate.setFont(font)
        self.lb_baudrate.setObjectName("lb_baudrate")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lb_baudrate)
        self.cbb_baudrate = QtWidgets.QComboBox(self.frame_comport_2)
        self.cbb_baudrate.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbb_baudrate.setStyleSheet("color: rgb(255, 255, 255);")
        self.cbb_baudrate.setObjectName("cbb_baudrate")
        self.cbb_baudrate.addItem("")
        self.cbb_baudrate.addItem("")
        self.cbb_baudrate.addItem("")
        self.cbb_baudrate.addItem("")
        self.cbb_baudrate.setItemText(3, "")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cbb_baudrate)
        self.lb_status_connect_port = QtWidgets.QLabel(self.frame_comport_2)
        self.lb_status_connect_port.setObjectName("lb_status_connect_port")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.lb_status_connect_port)
        self.gridLayout.addWidget(self.frame_comport_2, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_setting)
        self.stackedWidget.addWidget(self.form_control)
        self.form_information = QtWidgets.QWidget()
        self.form_information.setObjectName("form_information")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.form_information)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_info_2 = QtWidgets.QFrame(self.form_information)
        self.frame_info_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.frame_info_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info_2.setObjectName("frame_info_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_info_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lb_copyright = QtWidgets.QLabel(self.frame_info_2)
        self.lb_copyright.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lb_copyright.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lb_copyright.setObjectName("lb_copyright")
        self.verticalLayout_7.addWidget(self.lb_copyright)
        self.verticalLayout_6.addWidget(self.frame_info_2)
        self.stackedWidget.addWidget(self.form_information)
        self.horizontalLayout_11.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.center_main)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMinimumSize(QtCore.QSize(0, 0))
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 30))
        self.main_footer.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-top-color: solid 1px rgb(0, 0, 0);\n"
"}\n"
"")
        self.main_footer.setFrameShape(QtWidgets.QFrame.Panel)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.main_footer)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.main_footer)
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.form_botton_btn = QtWidgets.QWidget()
        self.form_botton_btn.setStyleSheet("QPushButton {\n"
"    padding: 15px 10px;\n"
"    border: none;\n"
"    border-radius:10px;\n"
"    background-color:#000;\n"
"    color:#fff;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 97, 157);\n"
"}")
        self.form_botton_btn.setObjectName("form_botton_btn")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.form_botton_btn)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.title_frame_bottom = QtWidgets.QFrame(self.form_botton_btn)
        self.title_frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame_bottom.setObjectName("title_frame_bottom")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.title_frame_bottom)
        self.horizontalLayout_8.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame = QtWidgets.QFrame(self.title_frame_bottom)
        self.frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_status = QtWidgets.QFrame(self.frame)
        self.frame_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_status.setObjectName("frame_status")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_status)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_4.addWidget(self.frame_status)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(15)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_4.addWidget(self.frame_3)
        self.horizontalLayout_8.addWidget(self.frame)
        self.horizontalLayout_7.addWidget(self.title_frame_bottom)
        self.stackedWidget_2.addWidget(self.form_botton_btn)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_2.addWidget(self.page_4)
        self.horizontalLayout_6.addWidget(self.stackedWidget_2)
        self.verticalLayout.addWidget(self.main_footer)
        self.main_body.raise_()
        self.main_footer.raise_()
        self.main_header.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Control HUBMOTOR RS485"))
        self.btn_home.setText(_translate("MainWindow", "Home"))
        self.btn_setting.setText(_translate("MainWindow", "Cài Đặt"))
        self.btn_information.setText(_translate("MainWindow", "Thông Tin"))
        self.txt_endcoder_left.setText(_translate("MainWindow", "0"))
        self.txt_encoder_right.setText(_translate("MainWindow", "0"))
        self.lb_encoderticks.setText(_translate("MainWindow", "Encoder Ticks:"))
        self.btn_getencoder.setText(_translate("MainWindow", "Get data encoder"))
        self.lb_mode.setText(_translate("MainWindow", "MODE:"))
        self.btn_speedmode.setText(_translate("MainWindow", "Speed Mode"))
        self.btn_positionmode.setText(_translate("MainWindow", "Position Mode"))
        self.lb_idle.setText(_translate("MainWindow", "Spindle MODE"))
        self.btn_idle.setText(_translate("MainWindow", "IDLE"))
        self.btn_enablemotor.setText(_translate("MainWindow", "ENABLE"))
        self.btn_checkvolt.setText(_translate("MainWindow", "Check Volt:"))
        self.lb_volt.setText(_translate("MainWindow", "..."))
        self.lb_expand.setText(_translate("MainWindow", "Mở rộng"))
        self.btn_xoay.setText(_translate("MainWindow", "Xoay Mode"))
        self.lb_testcontrol.setText(_translate("MainWindow", "CONTROL"))
        self.lb_sp.setText(_translate("MainWindow", "Speed (RPM):"))
        self.txt_speed.setText(_translate("MainWindow", "5"))
        self.btn_left.setText(_translate("MainWindow", "LEFT"))
        self.btn_forward.setText(_translate("MainWindow", "FORWARD"))
        self.btn_right.setText(_translate("MainWindow", "RIGHT"))
        self.btn_stop.setText(_translate("MainWindow", "STOP"))
        self.btn_backward.setText(_translate("MainWindow", "BACKWARD"))
        self.btn_keypad.setText(_translate("MainWindow", "Keyboard"))
        self.lb_left.setText(_translate("MainWindow", "RPM_LEFT"))
        self.lb_right.setText(_translate("MainWindow", "RPM_RIGHT"))
        self.txt_left.setText(_translate("MainWindow", "5"))
        self.txt_right.setText(_translate("MainWindow", "-5"))
        self.btn_runspeed.setText(_translate("MainWindow", "RUN"))
        self.lb_testcontrol_2.setText(_translate("MainWindow", "TEST CONTROL"))
        self.lb_portInfo.setText(_translate("MainWindow", "PORT"))
        self.lb_nameport.setText(_translate("MainWindow", "Com_Port"))
        self.lb_baudrate.setText(_translate("MainWindow", "Baud_rate"))
        self.cbb_baudrate.setItemText(0, _translate("MainWindow", "115200"))
        self.cbb_baudrate.setItemText(1, _translate("MainWindow", "9600"))
        self.cbb_baudrate.setItemText(2, _translate("MainWindow", "57600"))
        self.lb_status_connect_port.setText(_translate("MainWindow", "..."))
        self.lb_copyright.setText(_translate("MainWindow", "Copyright: VJMODERN - Electronic TrungLe"))
import icon_navigation_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
